import Joi from "joi";

export default {
  buscarSaveDocumento: Joi.object().keys({
    aux3: Joi.string().required(),
  }),
  cargarDiasPotencia: Joi.object().keys({
    ucp: Joi.string().required(),
  }),
  buscarVersioneSesion: Joi.object().keys({
    nombre: Joi.string().required(),
  }),
  agregarVersionSesion: Joi.object().keys({
    fecha: Joi.string().required(),
    ucp: Joi.string().required(),
    fechainicio: Joi.string().required(),
    fechafin: Joi.string().required(),
    tipodatos: Joi.string().required(),
    tendencia: Joi.string().required(),
    dias: Joi.string().required(),
    edicionfiltro: Joi.string().required(),
    edicionperiodo: Joi.string().required(),
    ediciontexto: Joi.string().required(),
    edicionfecha: Joi.string().required(),
    edicionsuma: Joi.string().required(),
    nombre: Joi.string().required(),
    version: Joi.string().required(),
    usuario: Joi.string().required(),
    p1_diario: Joi.string().required(),
    p2_diario: Joi.string().required(),
    p3_diario: Joi.string().required(),
    p4_diario: Joi.string().required(),
    p5_diario: Joi.string().required(),
    p6_diario: Joi.string().required(),
    p7_diario: Joi.string().required(),
    p8_diario: Joi.string().required(),
    p9_diario: Joi.string().required(),
    p10_diario: Joi.string().required(),
    p11_diario: Joi.string().required(),
    p12_diario: Joi.string().required(),
    p13_diario: Joi.string().required(),
    p14_diario: Joi.string().required(),
    p15_diario: Joi.string().required(),
    p16_diario: Joi.string().required(),
    p17_diario: Joi.string().required(),
    p18_diario: Joi.string().required(),
    p19_diario: Joi.string().required(),
    p20_diario: Joi.string().required(),
    p21_diario: Joi.string().required(),
    p22_diario: Joi.string().required(),
    p23_diario: Joi.string().required(),
    p24_diario: Joi.string().required(),
    nombrearchivo: Joi.string().required(),
    cargaindustrial: Joi.string().required(),
  }),
  agregarDatosPronosticoxSesion: Joi.object().keys({
    codsesion: Joi.string().required(),
    check_f: Joi.string().required(),
    fecha: Joi.string().required(),
    p1: Joi.string().required(),
    p2: Joi.string().required(),
    p3: Joi.string().required(),
    p4: Joi.string().required(),
    p5: Joi.string().required(),
    p6: Joi.string().required(),
    p7: Joi.string().required(),
    p8: Joi.string().required(),
    p9: Joi.string().required(),
    p10: Joi.string().required(),
    p11: Joi.string().required(),
    p12: Joi.string().required(),
    p13: Joi.string().required(),
    p14: Joi.string().required(),
    p15: Joi.string().required(),
    p16: Joi.string().required(),
    p17: Joi.string().required(),
    p18: Joi.string().required(),
    p19: Joi.string().required(),
    p20: Joi.string().required(),
    p21: Joi.string().required(),
    p22: Joi.string().required(),
    p23: Joi.string().required(),
    p24: Joi.string().required(),
    observacion: Joi.string().required(),
    tipo: Joi.string().required(),
  }),
  buscarDiaFestivo: Joi.object().keys({
    fecha: Joi.string().required(),
    ucp: Joi.string().required(),
  }),
  listarFestivosPorRango: Joi.object({
    fechaInicio: Joi.string().isoDate().required(),
    fechaFin: Joi.string().isoDate().required(),
    ucp: Joi.number().integer().required(),
  }),
  buscarPotenciaDia: Joi.object().keys({
    ucp: Joi.string().required(),
    dia: Joi.number().required(),
  }),
  cargarPeriodosxUCPDesdeFecha: Joi.object().keys({
    ucp: Joi.string().required(),
    fechaInicio: Joi.string().required(),
  }),
  cargarPeriodosxUCPxUnaFechaxLimite: Joi.object().keys({
    ucp: Joi.string().required(),
    fechaInicio: Joi.string().required(),
    limite: Joi.number().required(),
  }),
  actualizarDiaPotencia: Joi.object().keys({
    codigo: Joi.number().required(),
    dia: Joi.number().required(),
    potencia1: Joi.number().required(),
    potencia2: Joi.number().required(),
    potencia3: Joi.number().required(),
    potencia4: Joi.number().required(),
    potencia5: Joi.number().required(),
    potencia6: Joi.number().required(),
    potencia7: Joi.number().required(),
    ucp: Joi.string().required(),
  }),
  crearDiaPotencia: Joi.object().keys({
    dia: Joi.number().required(),
    potencia1: Joi.number().required(),
    potencia2: Joi.number().required(),
    potencia3: Joi.number().required(),
    potencia4: Joi.number().required(),
    potencia5: Joi.number().required(),
    potencia6: Joi.number().required(),
    potencia7: Joi.number().required(),
    ucp: Joi.string().required(),
  }),
  agregarUCPMedida: Joi.object().keys({
    nombre: Joi.string().allow(null, ""),
    factor: Joi.number().allow(null, ""),
    codigo_rpm: Joi.string().allow(null),
    codpadre: Joi.number().integer().allow(null),
    estado: Joi.number().required(),
    aux: Joi.string().allow(null, ""),
    aux2: Joi.string().allow(null, ""),
    aux3: Joi.string().allow(null, ""),
    aux4: Joi.string().allow(null, ""),
  }),
  actualizarUCPMedida: Joi.object().keys({
    codigo: Joi.number().required(),
    nombre: Joi.string().allow(null, ""),
    factor: Joi.number().allow(null).required(),
    codigo_rpm: Joi.string().allow(null),
    codpadre: Joi.number().integer().allow(null),
    estado: Joi.number().required(),
    aux: Joi.string().allow(null, ""),
    aux2: Joi.string().allow(null, ""),
    aux3: Joi.string().allow(null, ""),
    aux4: Joi.string().allow(null, ""),
  }),
  eliminarUCPMedidaParams: Joi.object().keys({
    codigo: Joi.number().required(),
  }),
  cargarUCP: Joi.object().keys({
    codpadre: Joi.number().integer().optional().default(0),
    estado: Joi.number().integer().optional().default(1),
  }),
  editarMercado: Joi.object().keys({
    mc: Joi.string().trim().required(),
    mcnuevo: Joi.string().trim().required(),
  }),
  cargarUmbralSchema: Joi.object().keys({
    codpadre: Joi.number().integer().optional().default(79),
    estado: Joi.number().integer().optional().default(1),
  }),
  editarUmbralSchema: Joi.object().keys({
    codigo: Joi.number().integer().required(),
    aux2: Joi.alternatives()
      .try(Joi.string().allow(""), Joi.number())
      .required(),
  }),
  cargarDiasFestivosSchema: Joi.object().keys({
    anio: Joi.number().integer().min(1900).required(),
    ucp: Joi.string().required(),
  }),
  ingresarDiaFestivosSchema: Joi.object().keys({
    ucp: Joi.string().required(),
    fecha: Joi.string().isoDate().required(), // recibir ISO yyyy-mm-dd
  }),
  borrarDiaFestivosSchema: Joi.object().keys({
    codigo: Joi.number().integer().required(),
  }),
  buscarDiaFestivoSchema: Joi.object().keys({
    fecha: Joi.string().isoDate().required(),
    ucp: Joi.string().required(),
  }),
  buscarUltimaFechaHistorica: Joi.object().keys({
    ucp: Joi.string().required(),
  }),
  buscarFactor: Joi.object().keys({
    codigo: Joi.string().required(),
  }),
  cargarCodigoRMPxUCP: Joi.object().keys({
    codpadre: Joi.string().required(),
  }),
  cargarTipoArchivos: Joi.object().keys({
    estado: Joi.number().integer().optional().default(1),
    aux2: Joi.string().required(),
  }),
  cargarUCPxAux2: Joi.object().keys({
    aux2: Joi.string().required(),
  }),
  buscarUCPActualizacionDatos: Joi.object().keys({
    ucp: Joi.string().required(),
    fecha: Joi.string().required(),
  }),
  verificarExisteActualizacionDatos: Joi.object().keys({
    ucp: Joi.string().required(),
    fecha: Joi.string().required(),
  }),
  agregarUCPActualizacionDatos: Joi.object().keys({
    ucp: Joi.string().required(),
    fecha: Joi.string().required(),
    observacion: Joi.string().optional().allow(""),
    p1: Joi.number().required(),
    p2: Joi.number().required(),
    p3: Joi.number().required(),
    p4: Joi.number().required(),
    p5: Joi.number().required(),
    p6: Joi.number().required(),
    p7: Joi.number().required(),
    p8: Joi.number().required(),
    p9: Joi.number().required(),
    p10: Joi.number().required(),
    p11: Joi.number().required(),
    p12: Joi.number().required(),
    p13: Joi.number().required(),
    p14: Joi.number().required(),
    p15: Joi.number().required(),
    p16: Joi.number().required(),
    p17: Joi.number().required(),
    p18: Joi.number().required(),
    p19: Joi.number().required(),
    p20: Joi.number().required(),
    p21: Joi.number().required(),
    p22: Joi.number().required(),
    p23: Joi.number().required(),
    p24: Joi.number().required(),
    estado: Joi.string().required(),
    festivo: Joi.number().required(),
  }),
  actualizarUCPActualizacionDatos: Joi.object().keys({
    p1: Joi.number().required(),
    p2: Joi.number().required(),
    p3: Joi.number().required(),
    p4: Joi.number().required(),
    p5: Joi.number().required(),
    p6: Joi.number().required(),
    p7: Joi.number().required(),
    p8: Joi.number().required(),
    p9: Joi.number().required(),
    p10: Joi.number().required(),
    p11: Joi.number().required(),
    p12: Joi.number().required(),
    p13: Joi.number().required(),
    p14: Joi.number().required(),
    p15: Joi.number().required(),
    p16: Joi.number().required(),
    p17: Joi.number().required(),
    p18: Joi.number().required(),
    p19: Joi.number().required(),
    p20: Joi.number().required(),
    p21: Joi.number().required(),
    p22: Joi.number().required(),
    p23: Joi.number().required(),
    p24: Joi.number().required(),
    estado: Joi.string().required(),
    observacion: Joi.string().optional().allow(""),
    ucp: Joi.string().required(),
    fecha: Joi.string().required(),
    festivo: Joi.number().required(),
  }),
  buscarClimaPeriodos: Joi.object().keys({
    ucp: Joi.string().required(),
    fecha: Joi.string().isoDate().required(),
  }),

  agregarClimaPronosticoLog: Joi.object().keys({
    fecha: Joi.string().isoDate().required(),
    ucp: Joi.string().required(),
  }),

  agregarClimaPeriodo: Joi.object().keys({
    fecha: Joi.string().isoDate().required(),
    ucp: Joi.string().required(),
    indice: Joi.number().integer().min(1).required(),
    clima: Joi.string().required(),
    valor: Joi.string().required(),
  }),

  actualizarClimaPeriodos: Joi.object().keys({
    fecha: Joi.string().isoDate().required(),
    ucp: Joi.string().required(),
    indice: Joi.number().integer().min(1).required(),
    clima: Joi.string().required(),
    valor: Joi.string().required(),
  }),

  buscarTipicidad: Joi.object().keys({
    ucp: Joi.string().required(),
    fecha: Joi.string().isoDate().required(),
  }),

  listarTipoModeloPorRango: Joi.object({
    fechaInicio: Joi.string().isoDate().required(),
    fechaFin: Joi.string().isoDate().required(),
    ucp: Joi.number().integer().required(),
  }),

  insertarTipoPronostico: Joi.object({
    ucp: Joi.string().required(),
    fecha: Joi.string().isoDate().required(),
    tipopronostico: Joi.string().required(),
  }),

  cargarPeriodosDinamico: Joi.object({
    ucp: Joi.string().required(),
    fechaInicio: Joi.string().required(),
    fechaFin: Joi.string().required(),
    diasSemana: Joi.array().items(Joi.number().min(0).max(6)).optional(),
    festivo: Joi.boolean().optional(),
  }),
};
